
# load required Functions
source("~/R-Projects/DFC/R/Source/addTicker.R")
source("~/R-Projects/DFC/R/Source/calcPaidTax.R")
source("~/R-Projects/DFC/R/Source/formatBBU.R")
source("~/R-Projects/DFC/R/Source/formatCsv.R")
source("~/R-Projects/DFC/R/Source/getAccruedFees.R")
source("~/R-Projects/DFC/R/Source/getAllCash.R")
source("~/R-Projects/DFC/R/Source/getCashMvmt.R")
source("~/R-Projects/DFC/R/Source/getCashPos.R")
source("~/R-Projects/DFC/R/Source/getData.R")
source("~/R-Projects/DFC/R/Source/getNavData.R")
source("~/R-Projects/DFC/R/Source/getPendingDiv.R")
source("~/R-Projects/DFC/R/Source/getSecurityPos.R")
source("~/R-Projects/DFC/R/Source/getFxFwd.R")
